version: '3'

services:
  doorbash.website:
    image: doorbash.website
    build:
      context: ./DoorBash.WebSite
      dockerfile: Dockerfile

  webapi:
    image: webapi
    build:
      context: ./../WebApi
      dockerfile: Dockerfile
